blank_issues_enabled: false
contact_links:
  - name: Lacesong Community Support
    url: https://github.com/pecan-solutions/lacesong/discussions
    about: Ask questions and get help from the community
  - name: Documentation
    url: https://github.com/pecan-solutions/lacesong/blob/main/docs/USAGE.md
    about: Check the usage guide for detailed instructions